The first test in addition_testing.py is the one that is failing.
This is due to line 12 when better_addition is called with
num_rechecks=0. The list sum_computations will thus have a length
of 0 and list index 0 in sum_computations[0] will be out of
range.
